[package]
name = "ymp-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
ymp-domain = { path = "../ymp-domain" }
ymp-kernel = { path = "../ymp-kernel" }
serde_json.workspace = true

[dev-dependencies]
serde.workspace = true

[lints]
workspace = true
