[package]
name = "ymp-agent-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
ymp-agent-api.workspace = true
ymp-application.workspace = true
ymp-domain.workspace = true

[dev-dependencies]
tempfile.workspace = true
ymp-agent-mcp.workspace = true
