[package]
name = "ymp-providers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
fs2.workspace = true
ymp-core.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
async-trait.workspace = true
libc.workspace = true

[dev-dependencies]
tempfile.workspace = true
