[package]
name = "ymp-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "ymp"
path = "src/main.rs"

[dependencies]
ymp-core.workspace = true
ymp-storage.workspace = true
ymp-providers.workspace = true
ymp-runtime.workspace = true
ymp-tui.workspace = true
anyhow.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
clap.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
