[package]
name = "ymp-tui-prototype"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "ymp-prototype"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
ratatui.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
serde.workspace = true
serde_json.workspace = true
fs2.workspace = true
tempfile.workspace = true
sha2.workspace = true
