[package]
name = "ymp-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "ymp"
path = "src/main.rs"

[dependencies]
signal-hook = { version = "0.3.18", default-features = false }
ymp-runtime = { path = "../ymp-runtime" }
ymp-storage = { path = "../ymp-storage" }

[lints]
workspace = true
