#!/usr/bin/env python3
"""Maintain the repository's project task register; never starts an agent."""
import argparse
import collections
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REGISTER = ROOT / 'tasks.json'
STATUSES = ('proposed', 'ready', 'in_progress', 'blocked', 'parked', 'done', 'rejected')


def validate(data):
    tasks = data['tasks']
    ids = [t['id'] for t in tasks]
    if len(ids) != len(set(ids)):
        raise ValueError('Duplicate task ID')
    by_id = {t['id']: t for t in tasks}
    for task in tasks:
        if task['status'] not in STATUSES:
            raise ValueError(f"Invalid status: {task['id']}")
        if not task['acceptance'] or not task['title']:
            raise ValueError(f"Missing task definition: {task['id']}")
        for dep in task['depends_on']:
            if dep not in by_id:
                raise ValueError(f"Unknown dependency: {dep}")
        if task['status'] == 'done' and not task['evidence']:
            raise ValueError(f"Completion requires evidence: {task['id']}")
    visited, visiting = set(), set()
    def visit(key):
        if key in visiting:
            raise ValueError('Dependency cycle at ' + key)
        if key in visited:
            return
        visiting.add(key)
        for dep in by_id[key]['depends_on']:
            visit(dep)
        visiting.remove(key)
        visited.add(key)
    for key in ids:
        visit(key)
    for key in data.get('delivery_order', []):
        if key not in by_id:
            raise ValueError('Unknown delivery task: ' + key)
    return by_id


def write_atomic(path, text):
    temporary = path.with_suffix(path.suffix + '.tmp')
    temporary.write_text(text)
    temporary.replace(path)


def render(data, save=True):
    counts = collections.Counter(t['status'] for t in data['tasks'])
    lines = [
        '# ymp project tasks', '',
        'Updated: ' + data.get('updated_at', '2026-09-12') + '.', '',
        'This is the project task register. The canonical records are in [tasks.json](tasks.json); this page is generated by [manage.py](manage.py). It tracks development and research work without starting product sessions or agents.', '',
        'A research recommendation is not an implemented feature. Proposed implementation tasks require the decision stated in their authorization field. Real-provider experiments require their recorded quota budget to be approved. Research completion is reported separately from product delivery.', '',
        '## Progress', '',
        '| Work type | Done | Total |', '| --- | ---: | ---: |',
    ]
    for kind in sorted({t['type'] for t in data['tasks']}):
        group = [t for t in data['tasks'] if t['type'] == kind]
        lines.append(f"| {kind} | {sum(t['status'] == 'done' for t in group)} | {len(group)} |")
    lines += ['', ', '.join(f'{s}: {counts[s]}' for s in STATUSES if counts[s]), '', '## Current work', '']
    active = [t for t in data['tasks'] if t['status'] == 'in_progress']
    lines += [f"- [{t['id']}](#{t['id'].lower()}) — {t['title']}" for t in active] or ['No task is currently in progress.']
    if data.get('delivery_order'):
        lines += ['', '## Immediate proposed delivery', '', 'This order is a research recommendation. Authorization is recorded on each task.', '']
        by_id = {t['id']: t for t in data['tasks']}
        for position,key in enumerate(data['delivery_order'],1):
            task = by_id[key]
            lines.append(f"{position}. [{key}](#{key.lower()}) — {task['title']} ({task['status']}).")
    lines += ['', '## Board', '', '| ID | Priority | Status | Task | Dependencies |', '| --- | --- | --- | --- | --- |']
    for t in data['tasks']:
        deps = ', '.join(t['depends_on']) or 'None'
        lines.append(f"| [{t['id']}](#{t['id'].lower()}) | {t['priority']} | {t['status']} | {t['title']} | {deps} |")
    lines += ['', '## Updating progress', '', 'Run these commands from the repository root:', '', '~~~sh',
              'python3 ymp-docs/tasks/manage.py list', 'python3 ymp-docs/tasks/manage.py check',
              'python3 ymp-docs/tasks/manage.py status YMP-001 in_progress --note "Describe the current evidence or blocker"',
              'python3 ymp-docs/tasks/manage.py render', '~~~', '',
              'Edit task definitions and evidence links in tasks.json. Record implementation completion only after its acceptance criteria are met; done records must include evidence. Status updates preserve a dated history. Keep dependency and authorization decisions explicit.', '']
    for t in data['tasks']:
        lines += [f"## {t['id']}", '', t['title'], '',
                  f"**Type:** {t['type']} · **Priority:** {t['priority']} · **Status:** {t['status']}", '',
                  f"**Owner:** {t['owner']}", '', f"**Authorization:** {t['authorization']}", '',
                  '**Depends on:** ' + (', '.join(t['depends_on']) or 'None'), '',
                  t['reason'], '', '**Acceptance criteria:**', '']
        lines += ['- ' + a for a in t['acceptance']]
        lines += ['', '**Evidence:**', '']
        lines += ['- ' + e for e in t['evidence']] or ['- Pending.']
        if t.get('budget'):
            lines += ['', '**Experiment budget:** ' + t['budget']]
        if t.get('history'):
            lines += ['', '**Latest update:** ' + t['history'][-1]['note']]
        lines.append('')
    result = '\n'.join(lines)
    if save:
        write_atomic(ROOT / 'README.md', result)
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest='command', required=True)
    for name in ('list', 'check', 'render'):
        sub.add_parser(name)
    status = sub.add_parser('status')
    status.add_argument('id')
    status.add_argument('status', choices=STATUSES)
    status.add_argument('--note', required=True)
    args = parser.parse_args()
    data = json.loads(REGISTER.read_text())
    by_id = validate(data)
    if args.command == 'status':
        task = by_id[args.id]
        task['status'] = args.status
        task.setdefault('history', []).append({'at': datetime.now(timezone.utc).isoformat(), 'status': args.status, 'note': args.note})
        data['updated_at'] = datetime.now(timezone.utc).isoformat()
        validate(data)
        write_atomic(REGISTER, json.dumps(data, indent=2, ensure_ascii=False) + '\n')
        render(data)
    elif args.command == 'render':
        render(data)
    elif args.command == 'check':
        if (ROOT / 'README.md').read_text() != render(data, save=False):
            raise ValueError('The task page is stale. Run manage.py render.')
        print(f"Valid register: {len(by_id)} tasks; unique IDs and acyclic dependencies.")
    else:
        for t in data['tasks']:
            print(f"{t['id']}  {t['priority']}  {t['status']:12}  {t['title']}")


if __name__ == '__main__':
    main()
